version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: "DevOps_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "DevOps_SECRET_ACCESS_KEY"
phases:
  pre_build:
    commands:
      - echo Terraform init
      - terraform init
      - env
  build:
    commands:
      - echo Terraform apply....
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo $(basename ./terraform.tfstate)