version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: "DevOps_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "DevOps_SECRET_ACCESS_KEY"
phases:
  # install:
  #   commands:
  #     - echo Install Terraform...
  #     - sudo apt-get update
  #     - sudo apt-get install wget unzip
  #     - sudo wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
  #     - sudo unzip ./terraform_1.0.0_linux_amd64.zip -d /usr/local/bin
  #   finally:
  #     - echo Failed Install Terraform...
  pre_build:
    commands:
      - echo Terraform init
      - terraform init
      - env
  build:
    commands:
      - echo Terraform apply....
      - terraform apply -auto-approve
    finally:
      - echo Terraform apply failed.
  post_build:
    commands:
      - echo $(basename ./terraform.tfstate)
artifacts:
  files:
    - ./terraform.tfstate
  discard-paths: yes